services:
  frontend:
    image: chatconv-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "127.0.0.1:8080:8080"
    command: serve -s ./dist -p 8080
    depends_on:
      - backend
  backend:
    image: chatconv-prod
    ports:
      - "127.0.0.1:3000:3000"
    command: node ./dist/srv/index.js
