services:
  frontend:
    image: chatconv-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "5173:5173"
    command: serve -s ./dist -p 5173
    depends_on:
      - backend
  backend:
    image: chatconv-prod
    ports:
      - "3000:3000"
    command: node ./dist-ssr/index.js
