services:
  frontend:
    image: chatwork-converter
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "8200:8200"
    command: serve -s ./dist -p 8200
    depends_on:
      - backend
  backend:
    image: chatwork-converter
    restart: always
    ports:
      - "8201:8201"
    command: node ./dist-ssr/index.js
