services:
  frontend:
    build: .
    environment:
      - NODE_ENV=development
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - .:/usr/src/app
    command: npm run serve
    depends_on:
      - backend
  backend:
    image: chatconv-frontend
    environment:
      - NODE_ENV=development
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - .:/usr/src/app
    command: npm run express
