services:
  frontend:
    container_name: frontend-dev
    image: chatconv-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - .:/usr/src/app
    command: npm run serve
    depends_on:
      - backend
  backend:
    container_name: backend-dev
    image: chatconv-dev
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - .:/usr/src/app
    command: npm run express
